'use client';

/**
 * Copyright 2026 Kestrel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// 2.3 — AI trade review panel for closed journal entries.
// Lives in the analytics tab and lets the user request a post-trade review
// for any closed trade. The review is streamed from /api/journal/review.
import type { JournalEntry } from '@kestrel/shared';
import { IconAlertCircle, IconBolt, IconRefresh } from '@tabler/icons-react';
import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

import { Button } from '@/components/ui/button';
import { cn } from '@/lib/cn';
import { fetchCsrf } from '@/lib/csrf';

interface TradeReviewResponse {
  review: {
    review: string;
    modelId: string;
    inputTokens: number;
    outputTokens: number;
    costUsd: number;
    latencyMs: number;
  };
}

interface AiReviewPanelProps {
  entry: JournalEntry;
}

export function AiReviewPanel({ entry }: AiReviewPanelProps) {
  const [review, setReview] = useState<string | null>(null);
  const [modelId, setModelId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset review state when the entry changes so stale reviews aren't
  // shown for a different trade.
  useEffect(() => {
    setReview(null);
    setModelId(null);
    setError(null);
  }, [entry.id]);

  async function generateReview() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetchCsrf('/api/journal/review', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id: entry.id }),
      });
      const body = (await res.json()) as { error?: { message: string } } | TradeReviewResponse;
      if (!res.ok) {
        throw new Error(
          'error' in body && body.error?.message ? body.error.message : `HTTP ${res.status}`,
        );
      }
      const data = body as TradeReviewResponse;
      setReview(data.review.review);
      setModelId(data.review.modelId);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Review failed');
    } finally {
      setLoading(false);
    }
  }

  if (entry.outcome === 'open') {
    return (
      <div className="border-border bg-bg-elev-1 text-fg-subtle flex items-start gap-3 rounded-sm border p-4">
        <IconAlertCircle className="mt-0.5 size-5 shrink-0" />
        <p className="text-sm">Close this trade to unlock an AI-powered post-trade review.</p>
      </div>
    );
  }

  return (
    <div className="border-border bg-bg-elev-1 flex flex-col gap-4 rounded-sm border p-4">
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <IconBolt className="text-fg size-4" />
          <h3 className="text-fg text-sm font-semibold">AI Trade Review</h3>
        </div>
        <Button
          size="sm"
          variant="secondary"
          onClick={generateReview}
          loading={loading}
          disabled={loading}
          className="shrink-0"
        >
          {review ? (
            <>
              <IconRefresh className="size-4" />
              Regenerate
            </>
          ) : (
            <>
              <IconBolt className="size-4" />
              Generate Review
            </>
          )}
        </Button>
      </div>

      {error && (
        <div className="bg-danger/5 border-danger/20 text-danger flex items-start gap-2 rounded-sm border p-3 text-sm">
          <IconAlertCircle className="mt-0.5 size-4 shrink-0" />
          {error}
        </div>
      )}

      {review ? (
        <div className="flex flex-col gap-3">
          <div
            className={cn(
              'prose prose-sm prose-invert max-w-none',
              'text-fg [&_h2]:mt-4 [&_h2]:mb-2 [&_h2]:text-base [&_h2]:font-semibold',
              '[&_li]:mb-1 [&_ul]:list-disc [&_ul]:pl-5',
              '[&_p]:text-fg-subtle [&_p]:text-sm [&_p]:leading-[1.4]',
            )}
          >
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{review}</ReactMarkdown>
          </div>
          {modelId && (
            <p className="text-fg-muted text-xs">
              Generated by <span className="text-fg-subtle font-medium">{modelId}</span>
            </p>
          )}
        </div>
      ) : (
        <p className="text-fg-subtle text-sm">
          Get a concise post-trade breakdown: execution grade, risk management notes, process
          observations, and one action item for next time.
        </p>
      )}
    </div>
  );
}
