/**
 * Copyright 2026 Kestrel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Server-only secret-generation helpers. Split out from `./env.ts` so the
// `node:crypto` import doesn't leak into client bundles when they import
// `parseServerEnv` / `ServerEnv` types from `@kestrel/shared`.
//
// NOTE: we deliberately do NOT add `import 'server-only'` here. The
// `server-only` package's check fires whenever any transitive import
// reaches a client bundle (Next.js webpack flags it), and the biquote
// tests + env tests import this module directly. The split-file design
// is the actual guard: callers must opt into env-secrets via the
// explicit `@kestrel/shared/env-secrets` path (not the barrel), and the
// shared barrel does not re-export from here.

import { randomBytes } from 'node:crypto';

/**
 * Generate a cryptographically-strong random secret as hex.
 * Default length is 32 bytes (64 hex chars) — comfortably exceeds the
 * 32-char min on every secret schema.
 */
export function generateSecret(bytes = 32): string {
  return randomBytes(bytes).toString('hex');
}

/**
 * Names of secrets that may be auto-generated when missing in non-production.
 * Kept as a const tuple so callers can iterate without string-typing the
 * same names in two places.
 */
export const AUTO_GENERATED_SECRETS = [
  'NEXTAUTH_SECRET',
  'ENCRYPTION_SECRET',
  'CRON_SECRET',
] as const;
export type AutoGeneratedSecret = (typeof AUTO_GENERATED_SECRETS)[number];

/** Minimum bytes for each auto-generated secret (must exceed schema min). */
export const SECRET_MIN_BYTES: Record<AutoGeneratedSecret, number> = {
  NEXTAUTH_SECRET: 32, // schema min is 32 chars; 32 bytes hex = 64 chars
  ENCRYPTION_SECRET: 32, // schema min is 32 chars; encrypt.ts also requires exactly 32 bytes
  CRON_SECRET: 16, // schema min is 16 chars; 16 bytes hex = 32 chars
};

/**
 * L3 (RELIABILITY_AUDIT_REPORT.md) — canonical list of env vars that
 * the /api/health endpoint checks for. When adding new required env vars
 * to the project, keep this list in sync with the env validation schema
 * in `./env.ts`.
 */
export const REQUIRED_HEALTH_ENV_VARS = [
  'DATABASE_URL',
  'AUTH_COOKIE_SECRET',
  'CRON_SECRET',
] as const;
