#!/usr/bin/env node
/**
 * Copyright 2026 Kestrel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generate or complete the Docker .env file from secret-template.json.
 *
 *   node scripts/setup/lib/generate-env.mjs [--if-missing] [--file PATH]
 *
 * --if-missing  Exit without touching an existing file (init-secrets.sh).
 * --file PATH   Target path (default: <repo root>/.env).
 *
 * This is the SINGLE implementation behind both `pnpm setup` and
 * `docker/init-secrets.sh`, so the Docker path and the wizard path can
 * never drift apart.
 */
import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readEnvFile, upsertEnvFile } from './env.mjs';
import {
  hasAllSecrets,
  loadSecretTemplate,
  missingSecrets,
  resolveTemplateValue,
} from './secrets.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../../..');
const LEGACY_ENV_ALIASES = {
  HAMAFX_ENABLE_RLS: 'KESTREL_ENABLE_RLS',
};

// Cosmetic section grouping for freshly generated files. Every key listed
// here MUST exist in secret-template.json (enforced by tests).
const SECTIONS = [
  ['Postgres', ['POSTGRES_PASSWORD', 'POSTGRES_VOLUME_NAME']],
  [
    'Local Docker backups',
    [
      'BACKUP_VOLUME_NAME',
      'BACKUP_INTERVAL_SECONDS',
      'BACKUP_RETENTION_DAYS',
      'BACKUP_MAX_AGE_SECONDS',
    ],
  ],
  ['Langfuse (LLM observability)', ['LANGFUSE_NEXTAUTH_SECRET', 'LANGFUSE_SALT']],
  ['NextAuth (app authentication)', ['AUTH_SECRET', 'NEXTAUTH_URL']],
  ['Cron authentication', ['CRON_SECRET']],
  ['Worker health/proxy authentication', ['WORKER_HEALTH_TOKEN', 'BIQUOTE_PROXY_TOKEN']],
  ['Encryption (BYOK key encryption at rest)', ['ENCRYPTION_SECRET']],
  [
    'Safe self-hosted defaults',
    [
      'BYOK_ENABLED',
      'MULTI_USER_ENABLED',
      'REGISTRATION_MODE',
      'KESTREL_ENABLE_RLS',
      'OSS_SINGLE_USER_MODE',
    ],
  ],
];

function parseArgs(argv) {
  const flags = { file: null, ifMissing: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--if-missing') flags.ifMissing = true;
    else if (arg === '--file') flags.file = argv[++i] ?? null;
    else if (arg.startsWith('--file=')) flags.file = arg.slice('--file='.length);
  }
  return flags;
}

function renderFreshContent(template) {
  const lines = [
    '# Kestrel Docker deployment secrets',
    `# Generated by scripts/setup/lib/generate-env.mjs on ${new Date().toUTCString()}`,
    '# DO NOT commit this file — it is already in .gitignore.',
    '',
  ];
  for (const [section, keys] of SECTIONS) {
    lines.push(`# ── ${section} ${'─'.repeat(Math.max(0, 48 - section.length))}`);
    for (const key of keys) {
      if (!(key in template))
        throw new Error(
          `secret-template.json is missing "${key}" (listed in generate-env.mjs sections)`,
        );
      lines.push(`${key}=${resolveTemplateValue(template[key])}`);
    }
    lines.push('');
  }
  lines.push(`# Optional market data providers — add lines like FINNHUB_API_KEY=... here`);
  return `${lines.join('\n')}`;
}

async function main() {
  const flags = parseArgs(process.argv.slice(2));
  const target = flags.file ? resolve(flags.file) : resolve(REPO_ROOT, '.env');

  if (existsSync(target)) {
    if (flags.ifMissing) {
      console.log('✓ .env already exists — leaving it untouched.');
      console.log('  To regenerate, delete it first: rm .env');
      return 0;
    }
    const existing = readEnvFile(target).entries;
    const legacyAliasesPresent = Object.entries(LEGACY_ENV_ALIASES).some(([legacyKey]) =>
      existing.has(legacyKey),
    );
    if (hasAllSecrets(target) && !legacyAliasesPresent) {
      console.log('✓ .env already exists and is complete — leaving it untouched.');
      return 0;
    }
    const { missing } = missingSecrets(target);
    const migratedLegacyKeys = [];
    for (const [legacyKey, canonicalKey] of Object.entries(LEGACY_ENV_ALIASES)) {
      if (existing.has(legacyKey)) {
        // Preserve an operator's legacy value during the namespace migration
        // when the canonical key is absent. If both exist, canonical wins and
        // the deprecated alias is still removed for an unambiguous config.
        if (missing[canonicalKey] !== undefined) {
          missing[canonicalKey] = existing.get(legacyKey);
        }
        migratedLegacyKeys.push(legacyKey);
      }
    }
    const result = upsertEnvFile(target, missing, {
      backup: false,
      removeKeys: migratedLegacyKeys,
    });
    console.log(
      `✓ Completed missing secrets in .env (${result.diff.length} key${result.diff.length === 1 ? '' : 's'} added).`,
    );
    return 0;
  }

  const template = loadSecretTemplate();
  const content = renderFreshContent(template);
  writeFileSync(target, `${content}\n`, { mode: 0o600 });
  chmodSync(target, 0o600);
  console.log('✓ Generated .env with random secrets.');
  console.log('  Review it:  cat .env');
  console.log('  Now run:    docker compose up -d');
  console.log('  Optional:   docker compose --profile observability up -d');
  return 0;
}

const isMain =
  process.argv[1] && resolve(process.argv[1]) === resolve(__dirname, 'generate-env.mjs');
if (isMain) {
  const code = await main();
  process.exitCode = code;
}
